version: "3.8"

services:
  schools:
    build: .
    env_file:
      - .env
    ports:
      - "3002:3002"
    networks:
      - docker_network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schools
    networks:
      - docker_network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  docker_network:
    name: wulkanowy_network
